<a href="https://colab.research.google.com/github/giuseppefutia/BigDive2Gramsci/blob/master/graph_representation_ml_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Graph Representation for Machine Learning Using Numpy
Machine learning algorithms are able to process data in the form of matrices. For such reasons, we need to understand how we can represent graph using matrices.

Consider the following graph example:

![Graph example](http://graphonline.ru/tmp/saved/RF/RFAOxGXmjawkuiWO.png =300x)

We can represent this graph using the following matrices.

## Adjacency Matrix

An adjacency matrix is a square matrix used to represent a finite graph. The elements of the matrix indicate whether pairs of vertices are adjacent or not in the graph. If the graph is undirected, the adjacency matrix is symmetric. The adjacency matrix of our graph example is the following:

$\begin{bmatrix}
  0. & 1. & 1. & 1 \\ 
  1. & 0. & 0. & 0 \\ 
  1. & 0. & 0. & 1 \\ 
  1. & 0. & 1. & 0 \\ 
\end{bmatrix}$

## Incidence Matrix
An incidence matrix is a matrix that shows the relationship between two classes of objects (nodes and objects). Incidence matrices can describe directed and undirected graphs.

In graph theory, an undirected graph (like our example) can be represented using different types of incidence matrices:
* **unoriented incidence matrix**
* **oriented incidence matrix**

The unoriented incidence matrix (or simpy incidence matrix) is a $n × m$ matrix $B$, where $n$ and $m$ are the numbers of vertices and edges respectively, such that $B_{i,j} = 1$ if the vertex $v_i$ and edge $e_j$ are incident and 0 otherwise.

The (unoriented) incidence matrix of our graph example is the following:

$\begin{bmatrix}
  1. & 1. & 1. & 0 \\
  1. & 0. & 0. & 0 \\
  0. & 0. & 1. & 1 \\
  0. & 1. & 0. & 1 \\
\end{bmatrix}$

In this matrix we see that the sum of each column is equal to 2. This happens because all couples of vertices in the entire graph are linked by only one edge.


The incidence matrix of a directed graph is a $n × m$ matrix $B$ where $n$ and $m$ are the number of vertices and edges respectively, such that $B_{i,j} = −1$ if the edge $e_j$ leaves vertex $v_i$, 1 if it enters vertex $v_i$ and 0 otherwise


The oriented incidence matrix of an undirected graph is the incidence matrix, in the sense of directed graphs, of any orientation of the graph. That is, in the column of edge $e$, there is one $1$ in the row corresponding to one vertex of e and one $−1$ in the row corresponding to the other vertex of e, and all other rows have $0$. 

The oriented incidence matrix is unique up to negation of any of the columns, since negating the entries of a column corresponds to reversing the orientation of an edge.

The oriented incidence matrix of our graph example is the following:

$\begin{bmatrix}
  -1. & -1. & -1. &  0. \\
   1. &  0. &  0. &  0. \\
   0. &  0. &  1. & -1. \\
   0. &  1. &  0. & -1. \\
\end{bmatrix}$


## Degree Matrix
The degree matrix is a diagonal matrix which contains information about the degree of each vertex—that is, the number of edges attached to each vertex.

The degree is used together with the adjacency matrix to construct the Laplacian matrix of a graph (that we explore in the following section). The degree matrix of our graph example is the following: 

$\begin{bmatrix}
  3. & 0. & 0. & 0 \\ 
  0. & 1. & 0. & 0 \\ 
  0. & 0. & 2. & 0 \\ 
  0. & 0. & 0. & 2 \\ 
\end{bmatrix}$

## Laplacian Matrix
The Laplacian matrix, sometimes called admittance matrix, Kirchhoff matrix or discrete Laplacian, is a matrix representation of a graph. It can be used to calculate the number of spanning trees for a given graph and to to construct low dimensional embeddings, which can be useful for a variety of machine learning applications.

Given a simple graph $G$ with $n$ vertices, its Laplacian matrix ${\textstyle L_{n\times n}} $ is defined as:

* ${\displaystyle L=D-A,}$ where $D$ is the degree matrix and $A$ is the adjacency matrix of the graph.
* $L = I * I.T$ where $I$ is the oriented incidence matrix of our undirected graph.

Let's see the representation of the laplacian matrix with the degree matrix and the adjacency matrix, on the one side, and with the oriented incidence matrix, on the other side. We exploit numpy and make some tests using networkx. 


In [1]:
import numpy as np
import networkx as nx

# Adjacency matrix
A = np.matrix([
    [0, 1, 1, 1],
    [1, 0, 0, 0], 
    [1, 0, 0, 1],
    [1, 0, 1, 0]],
    dtype=float
)

print()
print()
print('Adjacency matrix')
print(A)

# Incidence matrix (unoriented)
I_u = np.matrix([
    [1, 1, 1, 0],
    [1, 0, 0, 0],
    [0, 0, 1, 1],
    [0, 1, 0, 1]],
    dtype=float
)

print()
print()
print('Incidence matrix (unoriented)')
print(I_u)

# Incidence matrix (oriented)
I_o = np.matrix([
    [-1, -1, -1,  0],
    [ 1,  0,  0,  0],
    [ 0,  0,  1, -1],
    [ 0,  1,  0,  1]],
    dtype=float
)

print()
print()
print('Incidence matrix (oriented)')
print(I_o)

# Degree matrix
D = np.matrix([
    [3, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 2, 0],
    [0, 0, 0, 2]],
    dtype=float
)

print()
print()
print('Degree matrix')
print(D)

# The degree matrix can be computed from the adjacency matrix
D_from_A = np.array(np.sum(A, axis=0))[0]
D_from_A = np.matrix(np.diag(D_from_A))

print()
print()
print('Computed degree matrix from adjacency one')
print(D_from_A)

# Laplacian matrix computed with degree and adjacency matrices
L = D - A

print()
print()
print('Laplacian matrix computed with degree and adjacency matrices')
print(L)

# Laplacian matrix computed with the oriented incidence matrix
L = I_o * I_o.T

print()
print()
print('Laplacian matrix computed with the oriented incidence matrix')
print(L)

# Test using networkx
# Compute the networkx graph using the adjacency matrix
# Then compute the laplacian matrix
G = nx.from_numpy_matrix(A)
L = nx.laplacian_matrix(G)

print()
print()
print('Laplacian matrix computed with networkx')
print(L.toarray())



Adjacency matrix
[[0. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]]


Incidence matrix (unoriented)
[[1. 1. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 1.]
 [0. 1. 0. 1.]]


Incidence matrix (oriented)
[[-1. -1. -1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1. -1.]
 [ 0.  1.  0.  1.]]


Degree matrix
[[3. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Computed degree matrix from adjacency one
[[3. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Laplacian matrix computed with degree and adjacency matrices
[[ 3. -1. -1. -1.]
 [-1.  1.  0.  0.]
 [-1.  0.  2. -1.]
 [-1.  0. -1.  2.]]


Laplacian matrix computed with the oriented incidence matrix
[[ 3. -1. -1. -1.]
 [-1.  1.  0.  0.]
 [-1.  0.  2. -1.]
 [-1.  0. -1.  2.]]


Laplacian matrix computed with networkx
[[ 3. -1. -1. -1.]
 [-1.  1.  0.  0.]
 [-1.  0.  2. -1.]
 [-1.  0. -1.  2.]]


Through the observation of the laplacian matrix of a simple graph (no loop or multiple edges for each node), we can notice that


$L_{i,j}: = \begin{cases} deg(v_i) \qquad \text{ if } i=j \\
                                      -1 \qquad \qquad \text{ if } i \ne j  \\
                                      0 \qquad \qquad \text{ otherwise } \end{cases} $



### Symmetric Normalized Laplacian Matrix

We can also obtain the **symmetric normalized laplacian matrix**, that is defined as follows:

$L^{sym} := D^{-1/2}LD^{-1/2}=I-D^{-1/2}AD^{-1/2}$

The elements of this formula are the following:
* $D^{-1/2}$ is a diagonal matrix where diagonal values correspond to the reciprocal square root  of diagonal values in root (see the code below for more details) 
* $L$ is the laplacian matrix (not normalized)
* $I$ is the unit matrix
* $A$ is the adjacency *matrix*

Let's compute the symmetric normalized laplacian using numpy (and test the results using networkx):

In [2]:
import numpy as np
import networkx as nx

# Adjacency Matrix - Size (4,4)
A = np.matrix([
    [0, 1, 1, 1],
    [1, 0, 0, 0], 
    [1, 0, 0, 1],
    [1, 0, 1, 0]],
    dtype=float
)

print()
print()
print('Adjacency matrix')
print(A)

# The Degree Matrix can be computed from the Adjacency Matrix
D = np.array(np.sum(A, axis=0))[0]
D = np.matrix(np.diag(D))

print()
print()
print('Computed degree matrix from adjacency one')
print(D)

# Laplacian matrix
L = D-A

print()
print()
print('Laplacian matrix')
print(L)

# Symmetric normalized laplacian
# Issue: when I compute reciprocal of square roots of all matrix values I obtain
# inf in case of 0 (this happens in the cases where i!=j)
# For this reason, I need to apply a hack to obtain D^-1/2
# Here I show the computation of the left side of the equation
D_hat = 1 / np.sqrt(D)
D_hat = D_hat.diagonal()
D_hat = np.squeeze(np.asarray(D_hat))
D_hat = np.matrix(np.diag(D_hat))
L_left = D_hat * L * D_hat

print()
print()
print('Symmetric normalized laplacian matrix, left side of the equation')
print(L_left)

# Here I show the computation of the right side of the equation
# Construct the unit matrix
I = np.matrix([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])
L_right = I - D_hat * A * D_hat

print()
print()
print('Symmetric normalized laplacian matrix, right side of the equation')
print(L_right)

# To test the correctness of our numpy implementation we exploit the networkx library
# Numpy adjacency matrix as networkx graph
G = nx.from_numpy_matrix(A)
L = nx.laplacian_matrix(G)
N = nx.normalized_laplacian_matrix(G)

print()
print()
print('Symmetric normalized laplacian matrix using networkx (for checking)')
print(N.toarray())

L_sym = N.toarray()



Adjacency matrix
[[0. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]]


Computed degree matrix from adjacency one
[[3. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Laplacian matrix
[[ 3. -1. -1. -1.]
 [-1.  1.  0.  0.]
 [-1.  0.  2. -1.]
 [-1.  0. -1.  2.]]


Symmetric normalized laplacian matrix, left side of the equation
[[ 1.         -0.57735027 -0.40824829 -0.40824829]
 [-0.57735027  1.          0.          0.        ]
 [-0.40824829  0.          1.         -0.5       ]
 [-0.40824829  0.         -0.5         1.        ]]


Symmetric normalized laplacian matrix, right side of the equation
[[ 1.         -0.57735027 -0.40824829 -0.40824829]
 [-0.57735027  1.          0.          0.        ]
 [-0.40824829  0.          1.         -0.5       ]
 [-0.40824829  0.         -0.5         1.        ]]


Symmetric normalized laplacian matrix using networkx (for checking)
[[ 1.         -0.57735027 -0.40824829 -0.40824829]
 [-0.57735027  1.          0.          0.        ]
 [

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:40: RuntimeWarning: divide by zero encountered in true_divide


The elements of symmetric normalized laplacian matrix are given by:

$L^{sym}_{i,j}: = \begin{cases} 1 \qquad \qquad \qquad \qquad \text{ if } i=j \text{ and } deg(v_i) \neq 0\\
                                      -\frac{1}{\sqrt{deg(v_i) deg(v_j)}}  \qquad \text{ if } i \ne j  \\
                                      0 \qquad \qquad \qquad \qquad \text{ otherwise } \end{cases} $



### Random Walk Normalized Laplacian

The random walk normalized Laplacian is defined as:

$ L^{\text{rw}}:=D^{-1}L $

The name of the random-walk normalized Laplacian comes from the fact that this matrix is $ L^{\text{rw}}=I-P $, where $ P=D^{-1}A $ is simply the transition matrix of a random walker on the graph. 

Another definition is the following:

$ L^{\text{rw}} = I - D^{-1/2} (I - L^{sym}) D^{-1/2} $

Let's compute the random walk normalized laplacian in numpy: 

In [3]:
import numpy as np

# Adjacency matrix
A = np.matrix([
    [0, 1, 1, 1],
    [1, 0, 0, 0], 
    [1, 0, 0, 1],
    [1, 0, 1, 0]],
    dtype=float
)

print()
print()
print('Adjacency matrix')
print(A)

# The degree matrix can be computed from the adjacency matrix
D = np.array(np.sum(A, axis=0))[0]
D = np.matrix(np.diag(D))

print()
print()
print('Computed degree matrix from adjacency one')
print(D)

# Square root of degree matrix
D_sqrt = np.sqrt(D)
D_sqrt = D_sqrt.diagonal()
D_sqrt = np.squeeze(np.asarray(D_sqrt))
D_sqrt = np.matrix(np.diag(D_sqrt))

print()
print()
print('Square root of degree matrix')
print(D_sqrt)

# Laplacian matrix computed with degree and adjacency matrices
L = D - A

# Diagonal matrix where diagonal entries are reciprocal of the corresponding
# positive diagonal entries of the degree matrix
D_inv = 1 / D
D_inv = D_inv.diagonal()
D_inv = np.squeeze(np.asarray(D_inv))
D_inv = np.matrix(np.diag(D_inv))
L_rw = D_inv * L

# Random walk normalized laplacian
print()
print()
print('Random walk normalized laplacian (D_inv * L)')
print(L_rw)

P = D_inv * A
L_rw = I - P

print()
print()
print('Random walk normalized laplacian (I - P) where P = D_inv * A')
print(L_rw)

# To compute L_sym you need to run the previous window
L_rw = I - D_hat * (I - L_sym) * D_sqrt


print()
print()
print('Random walk normalized laplacian (I - D_hat * (I - L_sym) * D_sqrt)')
print(L_rw)



Adjacency matrix
[[0. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]]


Computed degree matrix from adjacency one
[[3. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Square root of degree matrix
[[1.73205081 0.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.41421356]]


Random walk normalized laplacian (D_inv * L)
[[ 1.         -0.33333333 -0.33333333 -0.33333333]
 [-1.          1.          0.          0.        ]
 [-0.5         0.          1.         -0.5       ]
 [-0.5         0.         -0.5         1.        ]]


Random walk normalized laplacian (I - P) where P = D_inv * A
[[ 1.         -0.33333333 -0.33333333 -0.33333333]
 [-1.          1.          0.          0.        ]
 [-0.5         0.          1.         -0.5       ]
 [-0.5         0.         -0.5         1.        ]]


Random walk normalized laplacian (I - D_hat * (I - L_sym) * D_sqrt)
[[ 1.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:42: RuntimeWarning: divide by zero encountered in true_divide


The matrix element of the random walk normalized laplacian are the following:

The elements of $L$ are given by:

$L^{sym}_{i,j}: = \begin{cases} 1 \qquad \qquad  \qquad \text{ if } i=j \text{ and } deg(v_i) \neq 0\\
                                      -\frac{1}{\sqrt{deg(v_i)}}  \qquad \text{ if } i \ne j \text{ and } v_i \text{ is adjacent to } v_j   \\
                                      0 \qquad \qquad \qquad  \text{ otherwise } \end{cases} $





## Random Walks on Graph to Compute the Reduce Adjacency Matrix
As an aside about random walks on graphs, consider a simple undirected graph. 

Consider the probability that the walker is at the vertex $i$ at time $t$, given the probability distribution that he was at vertex $j$ at time $t − 1$ (assuming a uniform chance of taking a step along any of the edges attached to a given vertex):

$p(t) = AD^{-1}p(t-1) $

This relation can be rewrite as follows:

$ D^{-1/2} p(t) = [D^{-1/2}AD^{-1/2}] D^{-1/2}p(t-1) $ 

$A_{\text{reduced}} = D^{-1/2}AD^{-1/2} $ is a symmetric matrix called the reduced adjacency matrix. So, taking steps on this random walk requires taking powers of $A_{\text{reduced}}$.



## Reduced Adjacency Matrix and Graph Convolutional Networks
To understand the role of reduced adjacency matrix in machine learning on graphs we have to pick the main principles behind Graph Convolutional Networks (GCNs) that are one of the most powerful machine learning models for graphs.

Let' s consider the [blog post of Thomas Kipf](https://tkipf.github.io/graph-convolutional-networks/) on the GCNs implementation.

As stated by Kipf, the propagation rule for each layer of a GCN is the following

$f(H^{(l)}, A) = \sigma \Big( \color{red}D^\color{red}{-1/2}\color{red}A\color{red}D^\color{red}{-1/2} H^{(l)}W^{(l)} \Big)$

Consider a single random walk step, we consider the power 1 of the $A_{\text{reduced}}$ matrix, that corresponds to taking the normalized average of neighboring node features.










## Resources
* Laplacin matrix on Wikipedia: https://en.wikipedia.org/wiki/Laplacian_matrix.
* Graph Convolutional Networks blog post: https://tkipf.github.io/graph-convolutional-networks/
